# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
# Fabric Properties
# check these on https://modmuss50.me/fabric.html
minecraft_version=26.3
loader_version=0.19.5
# Mod Properties
mod_version=1.2
maven_group=org.molodoyss
archives_base_name=xaeroatlases
# Dependencies
# check this on https://modmuss50.me/fabric.html
fabric_version=0.162.0+26.3
worldmap=1.47.0
minimap=26.6.0
yacl=3.9.7
mod_menu=21.0.0
placeholder_api=3.1.0-beta.1
java=25